### ISSUE TITLE
flexASIO_gui does not start when used again  ### error in the event display

### ISSUE THREAD

**Issue by TerminatorSAW2k** [flipswitchingmonkey/FlexASIO_GUI#36]
Hello, i have a Problem with this tool:

The flex asio gui does not start when used again.

How i can fix it?

This is the information I have from the event display:

Protokollname: Application
Quelle:        Windows Error Reporting
Datum:         24.10.2022 14:53:25
Ereignis-ID:   1001
Aufgabenkategorie:Keine
Ebene:         Informationen
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      DESKTOP-9GG4TR2
Beschreibung:
Fehlerbucket 1494313614435414010, Typ 4
Ereignisname: APPCRASH
Antwort: Nicht verfügbar
CAB-Datei-ID: 0

Problemsignatur:
P1: FlexASIOGUI.exe
P2: 1.0.0.0
P3: 62b2fac5
P4: KERNELBASE.dll
P5: 10.0.19041.2130
P6: b0fac6c9
P7: e0434352
P8: 000000000002cd29
P9: 
P10: 

Angefügte Dateien:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3FA8.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4268.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER42B7.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER42D4.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4314.tmp.txt

Diese Dateien befinden sich möglicherweise hier:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_FlexASIOGUI.exe_f0138a15e9cb96ec3edc8ed59928d49da24924d_adcf0c17_a4f9d6aa-d0d9-489c-95a8-63df4c19293c

Analysesymbol: 
Es wird erneut nach einer Lösung gesucht: 0
Berichts-ID: 450550fe-7790-44fa-8197-5a8870e999bb
Berichtstatus: 268435456
Bucket mit Hash: 8f87e7ef004374ecd4bcde50ab73effa
CAB-Datei-Guid: 0
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-10-24T12:53:25.3016368Z" />
    <EventRecordID>365521</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-9GG4TR2</Computer>
    <Security />
  </System>
  <EventData>
    <Data>1494313614435414010</Data>
    <Data>4</Data>
    <Data>APPCRASH</Data>
    <Data>Nicht verfügbar</Data>
    <Data>0</Data>
    <Data>FlexASIOGUI.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>62b2fac5</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.2130</Data>
    <Data>b0fac6c9</Data>
    <Data>e0434352</Data>
    <Data>000000000002cd29</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3FA8.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4268.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER42B7.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER42D4.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4314.tmp.txt</Data>
    <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_FlexASIOGUI.exe_f0138a15e9cb96ec3edc8ed59928d49da24924d_adcf0c17_a4f9d6aa-d0d9-489c-95a8-63df4c19293c</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>450550fe-7790-44fa-8197-5a8870e999bb</Data>
    <Data>268435456</Data>
    <Data>8f87e7ef004374ecd4bcde50ab73effa</Data>
    <Data>0</Data>
  </EventData>
</Event>

##################################################################################################
Protokollname: Application
Quelle:        Application Error
Datum:         24.10.2022 14:53:23
Ereignis-ID:   1000
Aufgabenkategorie:(100)
Ebene:         Fehler
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      DESKTOP-9GG4TR2
Beschreibung:
Name der fehlerhaften Anwendung: FlexASIOGUI.exe, Version: 1.0.0.0, Zeitstempel: 0x62b2fac5
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.2130, Zeitstempel: 0xb0fac6c9
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000002cd29
ID des fehlerhaften Prozesses: 0x3ec8
Startzeit der fehlerhaften Anwendung: 0x01d8e7a798ee229a
Pfad der fehlerhaften Anwendung: C:\Program Files\FlexASIOGUI\FlexASIOGUI.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 450550fe-7790-44fa-8197-5a8870e999bb
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-10-24T12:53:23.0996420Z" />
    <EventRecordID>365520</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-9GG4TR2</Computer>
    <Security />
  </System>
  <EventData>
    <Data>FlexASIOGUI.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>62b2fac5</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.2130</Data>
    <Data>b0fac6c9</Data>
    <Data>e0434352</Data>
    <Data>000000000002cd29</Data>
    <Data>3ec8</Data>
    <Data>01d8e7a798ee229a</Data>
    <Data>C:\Program Files\FlexASIOGUI\FlexASIOGUI.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>450550fe-7790-44fa-8197-5a8870e999bb</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
###########################################################

Protokollname: Application
Quelle:        .NET Runtime
Datum:         24.10.2022 14:53:22
Ereignis-ID:   1026
Aufgabenkategorie:Keine
Ebene:         Fehler
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      DESKTOP-9GG4TR2
Beschreibung:
Application: FlexASIOGUI.exe
CoreCLR Version: 6.0.1022.47605
.NET Version: 6.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: Cannot define table with key 'Nett.Parser.Builders.KeyChain' as the owner already contains a row for key 'input' of type 'table'.
   at Nett.Parser.Builders.TableBuilder.CreateStandardTable(RootTable root, StandardTableNode table, IHasComments comments)
   at Nett.Parser.Builders.TableBuilder.CreateTableOrArrayOfTables(RootTable root, TableNode table)
   at Nett.Parser.Builders.TableBuilder.Build(StartNode node, TomlSettings settings)
   at Nett.StreamTomlSerializer.Deserialize(Stream s, TomlSettings settings)
   at Nett.Toml.ReadFile(String filePath, TomlSettings settings)
   at Nett.Toml.ReadFile[T](String filePath, TomlSettings settings)
   at FlexASIOGUI.Form1.LoadFlexASIOConfig(String tomlPath) in C:\dev\FlexASIO_GUI\Form1.cs:line 63
   at FlexASIOGUI.Form1..ctor() in C:\dev\FlexASIO_GUI\Form1.cs:line 53
   at FlexASIOGUI.Program.Main() in C:\dev\FlexASIO_GUI\Program.cs:line 20

Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-10-24T12:53:22.6821363Z" />
    <EventRecordID>365519</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-9GG4TR2</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: FlexASIOGUI.exe
CoreCLR Version: 6.0.1022.47605
.NET Version: 6.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: Cannot define table with key 'Nett.Parser.Builders.KeyChain' as the owner already contains a row for key 'input' of type 'table'.
   at Nett.Parser.Builders.TableBuilder.CreateStandardTable(RootTable root, StandardTableNode table, IHasComments comments)
   at Nett.Parser.Builders.TableBuilder.CreateTableOrArrayOfTables(RootTable root, TableNode table)
   at Nett.Parser.Builders.TableBuilder.Build(StartNode node, TomlSettings settings)
   at Nett.StreamTomlSerializer.Deserialize(Stream s, TomlSettings settings)
   at Nett.Toml.ReadFile(String filePath, TomlSettings settings)
   at Nett.Toml.ReadFile[T](String filePath, TomlSettings settings)
   at FlexASIOGUI.Form1.LoadFlexASIOConfig(String tomlPath) in C:\dev\FlexASIO_GUI\Form1.cs:line 63
   at FlexASIOGUI.Form1..ctor() in C:\dev\FlexASIO_GUI\Form1.cs:line 53
   at FlexASIOGUI.Program.Main() in C:\dev\FlexASIO_GUI\Program.cs:line 20
</Data>
  </EventData>
</Event>

**Comment by AlpineWhite** [comment]
@TerminatorSAW2k, open your config.toml file. It will likely be full of 'Null' after setting via GUI. Delete the contents and paste the example from the FlexASIO github. Save.

FlexASIO GUI should now load. I saved a new test file as FlexASIOGUI.toml and the contents looked good so I am not sure what caused the initial error for me (FlexASIO_GUI not loading)

**Comment by TerminatorSAW2k** [comment]
Unfortunately, the suggestions don't help, it doesn't even generate the .toml files. 

Therefore, the error will not be due to a non-existent .toml file. 

I have also tested your solution, the gui overlay is displayed on the 
Client 1, on another PC it works perfectly.

**Comment by flipswitchingmonkey** [comment]
Looks like this may have to do with the Nett library which is not being developed any more. Will have to figure out how to easily replace it

**Comment by flipswitchingmonkey** [comment]
Give the 0.35 release a try. I've replace Nett with Tomlyn. Also, delete your current flexasio.toml file if possible (or rename it)
see: https://github.com/flipswitchingmonkey/FlexASIO_GUI/releases/tag/v0.35

**Comment by TerminatorSAW2k** [comment]
Hello, thank you for the quick update.

However, the error is still present on my client even after the new update.

I think it is also due to .net. 

Here are the errors from the event viewer:

Protokollname: Application
Quelle:        Application Error
Datum:         29.10.2022 12:14:09
Ereignis-ID:   1000
Aufgabenkategorie:(100)
Ebene:         Fehler
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      DESKTOP-9GG4TR2
Beschreibung:
Name der fehlerhaften Anwendung: FlexASIOGUI.exe, Version: 1.0.0.0, Zeitstempel: 0x6331eb0e
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.2130, Zeitstempel: 0xb0fac6c9
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000002cd29
ID des fehlerhaften Prozesses: 0x1e88
Startzeit der fehlerhaften Anwendung: 0x01d8eb7f2ea57ffe
Pfad der fehlerhaften Anwendung: C:\Program Files\FlexASIOGUI\FlexASIOGUI.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: b5aa1db3-c05e-4357-bd64-6d5d89c30320
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-10-29T10:14:09.4071469Z" />
    <EventRecordID>366651</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-9GG4TR2</Computer>
    <Security />
  </System>
  <EventData>
    <Data>FlexASIOGUI.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>6331eb0e</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.2130</Data>
    <Data>b0fac6c9</Data>
    <Data>e0434352</Data>
    <Data>000000000002cd29</Data>
    <Data>1e88</Data>
    <Data>01d8eb7f2ea57ffe</Data>
    <Data>C:\Program Files\FlexASIOGUI\FlexASIOGUI.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>b5aa1db3-c05e-4357-bd64-6d5d89c30320</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>


########################################


Protokollname: Application
Quelle:        .NET Runtime
Datum:         29.10.2022 12:14:09
Ereignis-ID:   1026
Aufgabenkategorie:Keine
Ebene:         Fehler
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      DESKTOP-9GG4TR2
Beschreibung:
Application: FlexASIOGUI.exe
CoreCLR Version: 6.0.1022.47605
.NET Version: 6.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: Tomlyn.TomlException: (12,1) : error : The key `input` is already defined at (3,1) with `[input]␍␤device = "Line (MG-XU)"` and cannot be redefined
(15,1) : error : The key `input.device` is already defined at (4,1) with `device = "Line (MG-XU)"` and cannot be redefined
(18,1) : error : The key `output` is already defined at (6,1) with `[output]␍␤device = "Line (MG-XU)"␍␤␍␤# Use WASAPI as the PortAudio host API backend.␍␤backend = "Windows WASAPI"␍␤bufferSizeSamples = 256` and cannot be redefined

   at FlexASIOGUI.Form1.LoadFlexASIOConfig(String tomlPath) in C:\dev\FlexASIO_GUI\Form1.cs:line 68
   at FlexASIOGUI.Form1..ctor() in C:\dev\FlexASIO_GUI\Form1.cs:line 55
   at FlexASIOGUI.Program.Main() in C:\dev\FlexASIO_GUI\Program.cs:line 20

Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-10-29T10:14:09.0426480Z" />
    <EventRecordID>366650</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-9GG4TR2</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: FlexASIOGUI.exe
CoreCLR Version: 6.0.1022.47605
.NET Version: 6.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: Tomlyn.TomlException: (12,1) : error : The key `input` is already defined at (3,1) with `[input]␍␤device = "Line (MG-XU)"` and cannot be redefined
(15,1) : error : The key `input.device` is already defined at (4,1) with `device = "Line (MG-XU)"` and cannot be redefined
(18,1) : error : The key `output` is already defined at (6,1) with `[output]␍␤device = "Line (MG-XU)"␍␤␍␤# Use WASAPI as the PortAudio host API backend.␍␤backend = "Windows WASAPI"␍␤bufferSizeSamples = 256` and cannot be redefined

   at FlexASIOGUI.Form1.LoadFlexASIOConfig(String tomlPath) in C:\dev\FlexASIO_GUI\Form1.cs:line 68
   at FlexASIOGUI.Form1..ctor() in C:\dev\FlexASIO_GUI\Form1.cs:line 55
   at FlexASIOGUI.Program.Main() in C:\dev\FlexASIO_GUI\Program.cs:line 20
</Data>
  </EventData>
</Event>

**Comment by flipswitchingmonkey** [comment]
strange :(

**Comment by TerminatorSAW2k** [comment]
The funny thing with my office PC (Client 2) runs the tool 1A without problems, even the new version.

**Comment by TerminatorSAW2k** [comment]
Hello I was able to solve my problem. 

Error 1 was with me I have 2 users USER Windows folder one with the name and one with info ... for the online Windows account.

But the FlexAsio Config file had to be in the **info user name**, then it was recognized correctly.

I'm just surprised that the Gui had not recognized the 2 Benutzerkonnten but only the account with the username without info...

My Asio LINK PRO routing software has apparently previously also blocked the GUI for normal call, this had only worked when I the Config FlexAsio file in the user account: "Info" had stored.

Now I can call the Gui directly in the Asio Link PRo at any time for configure and change as desired.

Thanks for your help and effort.

Translated with www.DeepL.com/Translator (free version)
